# Generated by Django 2.0.5 on 2018-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='external_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='node',
            name='region',
            field=models.CharField(choices=[('AF', 'AF'), ('AN', 'AN'), ('AS', 'AS'), ('EU', 'EU'), ('NA', 'NA'), ('OC', 'OC'), ('SA', 'SA'), ('DEFAULT', 'DEFAULT')], max_length=100),
        ),
    ]
