# Generated by Django 2.0.5 on 2018-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180517_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='deleted',
        ),
        migrations.AddField(
            model_name='node',
            name='stopped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='external_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='region',
            field=models.CharField(choices=[('AF', 'AF'), ('AN', 'AN'), ('AS', 'AS'), ('EU', 'EU'), ('NA', 'NA'), ('OC', 'OC'), ('SA', 'SA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='node',
            name='started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
