ц# Generated by Django 2.0.5 on 2018-05-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180517_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='last_sent_bytes',
            field=models.BigIntegerField(help_text='Последний замер объема отданного трафика с хоста', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_sent_bytes_dt',
            field=models.DateTimeField(help_text='Время последнего', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='prev_sent_bytes',
            field=models.BigIntegerField(help_text='Предыдущий замер объема отданного трафика с хоста', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='prev_sent_bytes_dt',
            field=models.DateTimeField(help_text='Время вредыдущего замера', null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='throughput',
            field=models.BigIntegerField(default=104857600, help_text='Максимальная пропускная способность хоста. В байтах.'),
            preserve_default=False,
        ),
    ]
