# Generated by Django 2.0.5 on 2018-08-16 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180520_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='SonmBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(blank=True, max_length=100)),
                ('task_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='sonmbid',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='core.Node'),
        ),
    ]
